stages:
  raw_pipeline:
    cmd: set PYTHONPATH=src && python src/cli.py download-all && python src/cli.py
      process-all
    deps:
    - src/cli.py
    outs:
    - data/interim/combined_fakenews_dataset.csv
    - data/raw

  preprocess_pipeline:
    cmd: python src/cli.py preprocess-all
    deps:
      - data/interim/combined_fakenews_dataset.csv
      - src/cli.py
      - src/data_preprocess/preprocessing.py  # incluye el script actualizado
    outs:
      - data/processed

