services:
  - type: web
    name: deamentis-backend
    runtime: python
    rootDir: app/backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
    plan: free

  - type: web
    name: deamentis-frontend
    runtime: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "app/frontend/build"
